"""link bookings to flights, add baggage allowance

Revision ID: 0b1da044c12c
Revises: 5eb46cad1193
Create Date: 2026-08-19 18:40:52.618026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1da044c12c'
down_revision: Union[str, Sequence[str], None] = '5eb46cad1193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `flight_number` is NOT NULL, and adding a NOT NULL column to a table that
    already has rows fails outright. So: add it nullable, backfill, then tighten
    the constraint. Existing rows get a sentinel because their flight is genuinely
    unknown -- there is no data to derive it from.
    """
    op.add_column(
        "bookings", sa.Column("flight_number", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "bookings",
        sa.Column("connecting_flight_number", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "bookings", sa.Column("checked_baggage", sa.String(length=50), nullable=True)
    )

    op.execute(
        "UPDATE bookings SET flight_number = 'UNKNOWN' WHERE flight_number IS NULL"
    )

    op.alter_column("bookings", "flight_number", nullable=False)
    op.create_index(
        op.f("ix_bookings_flight_number"), "bookings", ["flight_number"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_flight_number'), table_name='bookings')
    op.drop_column('bookings', 'checked_baggage')
    op.drop_column('bookings', 'connecting_flight_number')
    op.drop_column('bookings', 'flight_number')
    # ### end Alembic commands ###
